import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/about")({
  head: () => ({
    meta: [
      { title: "How this works — TheFullPicture.ai" },
      {
        name: "description",
        content:
          "How TheFullPicture.ai groups AI news into single stories, writes AI summaries, and tags tone, access and geography.",
      },
      { property: "og:title", content: "How this works — TheFullPicture.ai" },
      {
        property: "og:description",
        content: "AI-written summaries, human spot checks, and how our filters work.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: AboutPage,
});

function AboutPage() {
  return (
    <main className="mx-auto max-w-3xl px-4 py-12">
      <h1 className="font-serif text-4xl font-semibold">About TheFullPicture.ai</h1>
      <div className="mt-8 space-y-6 border-b border-border pb-8 text-base leading-relaxed text-muted-foreground">
        <p className="font-serif text-lg leading-relaxed text-foreground sm:text-xl">
          Most AI news is either too narrowly focused on product launches, or heavily skewed toward
          one region's perspective. If you work in policy, governance, HR, or leadership — or if you
          simply want to stay across the full AI landscape without the noise — The Full Picture is
          built for you.
        </p>
        <p className="font-serif text-lg leading-relaxed text-foreground sm:text-xl">
          Unlike the big AI newsletters that chase funding rounds and Silicon Valley news cycles,
          The Full Picture covers the full spectrum — research, regulation, ethics, business impact,
          and the future of work — with a genuinely global lens. Because AI doesn't just affect one
          part of the world, and neither should the conversation about it. We pay particular
          attention to Europe, where some of the most consequential AI regulation and governance
          decisions are being made right now.
        </p>
      </div>
      <div className="mt-8 space-y-6 text-base leading-relaxed text-muted-foreground">
        <section>
          <h2 className="font-serif text-xl font-semibold text-foreground">One story, many sources</h2>
          <p className="mt-2">
            When several outlets cover the same development, we show a single card rather than one
            card per outlet. Every outlet that contributed is listed underneath, with a padlock next
            to sources behind a paywall, so you can always go to the original reporting.
          </p>
        </section>
        <section>
          <h2 className="font-serif text-xl font-semibold text-foreground">
            Summaries are written by AI
          </h2>
          <p className="mt-2">
            Each summary on this site is generated by an AI model from the linked sources, and every
            card says so. AI summaries can miss nuance or get details wrong. Treat the summary as a
            pointer, and the linked sources as the record.
          </p>
        </section>
        <section>
          <h2 className="font-serif text-xl font-semibold text-foreground">Human spot checks</h2>
          <p className="mt-2">
            A sample of stories is queued for human review. Reviewers can approve a story as-is, or
            correct the summary and tags before approving. When a story turns out to be wrong or
            incomplete, we publish a follow-up and link it from the original card.
          </p>
        </section>
        <section>
          <h2 className="font-serif text-xl font-semibold text-foreground">What the tags mean</h2>
          <ul className="mt-2 space-y-2">
            <li>
              <strong className="text-foreground">Tone</strong> — Good, Useful, Bad or Ugly: a quick
              read on how the development lands, not a judgement of the reporting.
            </li>
            <li>
              <strong className="text-foreground">Topic</strong> — one or more subject areas, from
              models and research to policy, ethics and the future of work.
            </li>
            <li>
              <strong className="text-foreground">Geography</strong> — where the story mainly
              applies.
            </li>
            <li>
              <strong className="text-foreground">Access</strong> — whether you can read the
              underlying coverage for free.
            </li>
          </ul>
        </section>
        <section>
          <h2 className="font-serif text-xl font-semibold text-foreground">Filters and digests</h2>
          <p className="mt-2">
            Filters combine, and the page address updates as you change them, so any filtered view
            can be shared or bookmarked. Signed-in readers can save a combination as their default
            view, and readers can subscribe to TheFullPicture.ai's paid email digest built from the filters they have
            selected, for €25 per year or €3 per month. See the{" "}
            <Link to="/privacy" className="underline underline-offset-4">
              privacy policy
            </Link>{" "}
            for how that data is handled.
          </p>
        </section>
      </div>
    </main>
  );
}
