import { ExternalLink, Flag, Lock, Sparkles, ArrowUpRight } from "lucide-react";
import { formatDate, toneClass, topicClass, type Story } from "@/lib/news";

function Tag({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return (
    <span
      className={`inline-flex items-center rounded-full border px-2.5 py-1 text-[0.7rem] font-semibold ${className}`}
    >
      {children}
    </span>
  );
}

export function StoryCard({ story }: { story: Story }) {
  return (
    <article className="group border-b border-border py-10 first:pt-2">
      <div className="flex flex-wrap items-center gap-2">
        {story.tone && <Tag className={toneClass[story.tone]}>{story.tone}</Tag>}
        {story.topics.map((t) => (
          <Tag key={t} className={topicClass[t]}>
            {t}
          </Tag>
        ))}
        {story.geography && (
          <Tag className="border-geo-foreground bg-geo-foreground text-tone-contrast">{story.geography}</Tag>
        )}
        {story.access && (
          <Tag className="border-access-foreground bg-access-foreground text-tone-contrast">
            {story.access === "Paid" ? <Lock className="mr-1 h-3 w-3" /> : null}
            {story.access}
          </Tag>
        )}
      </div>

      <h2 className="mt-4 max-w-3xl font-serif text-2xl leading-[1.2] font-semibold text-foreground transition-colors group-hover:text-brand-accent sm:text-[2rem]">
        {story.headline}
      </h2>

      <p className="mt-3 max-w-3xl font-serif text-[1.05rem] leading-[1.75] text-muted-foreground">
        {story.ai_generated_summary}
      </p>

      <p className="mt-4 inline-flex items-center gap-1.5 text-[0.68rem] font-semibold tracking-[0.12em] text-brand-accent uppercase">
        <Sparkles className="h-3.5 w-3.5" />
        Summary generated by AI
      </p>

      {story.followUp && (
        <a
          href={`#story-${story.followUp.id}`}
           className="mt-4 flex items-start gap-2 rounded-md border border-brand-accent/30 bg-accent/60 px-4 py-3 text-sm text-accent-foreground"
        >
          <ArrowUpRight className="mt-0.5 h-4 w-4 shrink-0" />
          <span>
            Follow-up / correction: <span className="underline">{story.followUp.headline}</span>
          </span>
        </a>
      )}

      <div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-2 text-sm">
        <span className="text-muted-foreground">{formatDate(story.published_at)}</span>
        <span className="text-muted-foreground">·</span>
        <span className="text-muted-foreground">Sources:</span>
        {story.sources.map((s) => (
          <a
            key={s.id}
            href={s.source_url}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1 font-medium text-foreground underline decoration-border underline-offset-4 hover:decoration-foreground"
          >
            {s.source_name}
            {s.is_paywalled && <Lock className="h-3 w-3 text-muted-foreground" />}
            <ExternalLink className="h-3 w-3 text-muted-foreground" />
          </a>
        ))}
        <a
          href={`mailto:corrections@thefullpicture.ai?subject=${encodeURIComponent(`Issue with story: ${story.headline}`)}`}
          className="inline-flex items-center gap-1 text-muted-foreground underline decoration-border underline-offset-4 hover:text-foreground"
        >
          <Flag className="h-3 w-3" />
          Report an issue
        </a>
      </div>
    </article>
  );
}
