import { ExternalLink, Flag, Lock, Sparkles, ArrowUpRight } from "lucide-react";
import { formatDate, toneClass, topicClass, type Story } from "@/lib/news";

function Tag({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return (
    <span
      className={`inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-medium tracking-wide ${className}`}
    >
      {children}
    </span>
  );
}

export function StoryCard({ story }: { story: Story }) {
  return (
    <article className="border-b border-border py-8 first:pt-2">
      <div className="flex flex-wrap items-center gap-2">
        {story.tone && <Tag className={toneClass[story.tone]}>{story.tone}</Tag>}
        {story.topics.map((t) => (
          <Tag key={t} className={topicClass[t]}>
            {t}
          </Tag>
        ))}
        {story.geography && (
          <Tag className="border-geo-foreground bg-geo-foreground text-tone-contrast">{story.geography}</Tag>
        )}
        {story.access && (
          <Tag className="border-access-foreground bg-access-foreground text-tone-contrast">
            {story.access === "Paid" ? <Lock className="mr-1 h-3 w-3" /> : null}
            {story.access}
          </Tag>
        )}
      </div>

      <h2 className="mt-3 font-serif text-2xl leading-snug font-semibold text-foreground sm:text-3xl">
        {story.headline}
      </h2>

      <p className="mt-2 text-base leading-relaxed text-muted-foreground">
        {story.ai_generated_summary}
      </p>

      <p className="mt-3 inline-flex items-center gap-1.5 text-xs font-medium tracking-wide text-muted-foreground uppercase">
        <Sparkles className="h-3.5 w-3.5" />
        Summary generated by AI
      </p>

      {story.followUp && (
        <a
          href={`#story-${story.followUp.id}`}
          className="mt-3 flex items-start gap-2 rounded-md border border-accent-foreground/20 bg-accent px-3 py-2 text-sm text-accent-foreground"
        >
          <ArrowUpRight className="mt-0.5 h-4 w-4 shrink-0" />
          <span>
            Follow-up / correction: <span className="underline">{story.followUp.headline}</span>
          </span>
        </a>
      )}

      <div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-2 text-sm">
        <span className="text-muted-foreground">{formatDate(story.published_at)}</span>
        <span className="text-muted-foreground">·</span>
        <span className="text-muted-foreground">Sources:</span>
        {story.sources.map((s) => (
          <a
            key={s.id}
            href={s.source_url}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1 font-medium text-foreground underline decoration-border underline-offset-4 hover:decoration-foreground"
          >
            {s.source_name}
            {s.is_paywalled && <Lock className="h-3 w-3 text-muted-foreground" />}
            <ExternalLink className="h-3 w-3 text-muted-foreground" />
          </a>
        ))}
        <a
          href={`mailto:corrections@thefullpicture.ai?subject=${encodeURIComponent(`Issue with story: ${story.headline}`)}`}
          className="inline-flex items-center gap-1 text-muted-foreground underline decoration-border underline-offset-4 hover:text-foreground"
        >
          <Flag className="h-3 w-3" />
          Report an issue
        </a>
      </div>
    </article>
  );
}
