/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SubscribersRouteImport } from './routes/subscribers'
import { Route as SubscribeIndexRouteImport } from './routes/subscribe.index'
import { Route as SubscribeConfirmedRouteImport } from './routes/subscribe.confirmed'
import { Route as ApiNewsletterActionRouteImport } from './routes/api.newsletter.$action'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribersRoute = SubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeIndexRoute = SubscribeIndexRouteImport.update({
  id: '/subscribe/',
  path: '/subscribe/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeConfirmedRoute = SubscribeConfirmedRouteImport.update({
  id: '/subscribe/confirmed',
  path: '/subscribe/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterActionRoute = ApiNewsletterActionRouteImport.update({
  id: '/api/newsletter/$action',
  path: '/api/newsletter/$action',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/impressum': typeof ImpressumRoute
  '/privacy': typeof PrivacyRoute
  '/review': typeof ReviewRoute
  '/subscribers': typeof SubscribersRoute
  '/subscribe/confirmed': typeof SubscribeConfirmedRoute
  '/subscribe/': typeof SubscribeIndexRoute
  '/api/newsletter/$action': typeof ApiNewsletterActionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/impressum': typeof ImpressumRoute
  '/privacy': typeof PrivacyRoute
  '/review': typeof ReviewRoute
  '/subscribers': typeof SubscribersRoute
  '/subscribe/confirmed': typeof SubscribeConfirmedRoute
  '/subscribe': typeof SubscribeIndexRoute
  '/api/newsletter/$action': typeof ApiNewsletterActionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/impressum': typeof ImpressumRoute
  '/privacy': typeof PrivacyRoute
  '/review': typeof ReviewRoute
  '/subscribers': typeof SubscribersRoute
  '/subscribe/confirmed': typeof SubscribeConfirmedRoute
  '/subscribe/': typeof SubscribeIndexRoute
  '/api/newsletter/$action': typeof ApiNewsletterActionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/impressum'
    | '/privacy'
    | '/review'
    | '/subscribers'
    | '/subscribe/confirmed'
    | '/subscribe/'
    | '/api/newsletter/$action'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/impressum'
    | '/privacy'
    | '/review'
    | '/subscribers'
    | '/subscribe/confirmed'
    | '/subscribe'
    | '/api/newsletter/$action'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/impressum'
    | '/privacy'
    | '/review'
    | '/subscribers'
    | '/subscribe/confirmed'
    | '/subscribe/'
    | '/api/newsletter/$action'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ImpressumRoute: typeof ImpressumRoute
  PrivacyRoute: typeof PrivacyRoute
  ReviewRoute: typeof ReviewRoute
  SubscribersRoute: typeof SubscribersRoute
  SubscribeConfirmedRoute: typeof SubscribeConfirmedRoute
  SubscribeIndexRoute: typeof SubscribeIndexRoute
  ApiNewsletterActionRoute: typeof ApiNewsletterActionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribers': {
      id: '/subscribers'
      path: '/subscribers'
      fullPath: '/subscribers'
      preLoaderRoute: typeof SubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe/': {
      id: '/subscribe/'
      path: '/subscribe'
      fullPath: '/subscribe/'
      preLoaderRoute: typeof SubscribeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe/confirmed': {
      id: '/subscribe/confirmed'
      path: '/subscribe/confirmed'
      fullPath: '/subscribe/confirmed'
      preLoaderRoute: typeof SubscribeConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter/$action': {
      id: '/api/newsletter/$action'
      path: '/api/newsletter/$action'
      fullPath: '/api/newsletter/$action'
      preLoaderRoute: typeof ApiNewsletterActionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ImpressumRoute: ImpressumRoute,
  PrivacyRoute: PrivacyRoute,
  ReviewRoute: ReviewRoute,
  SubscribersRoute: SubscribersRoute,
  SubscribeConfirmedRoute: SubscribeConfirmedRoute,
  SubscribeIndexRoute: SubscribeIndexRoute,
  ApiNewsletterActionRoute: ApiNewsletterActionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
